name: Build and publish

on:
  push:
    branches:
    - 'net8'
    - 'net8-*'
  pull_request:
    branches:
    - 'net8'
    - 'net8-*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'microsoft'
        java-version: '11'
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Install iOS and Android workload
      run: dotnet workload install ios android -s https://api.nuget.org/v3/index.json
    - name: Install older NuGet.exe
      run: |
        curl https://dist.nuget.org/win-x86-commandline/v5.8.1/nuget.exe --output nuget.exe
        chmod +x nuget.exe
    - name: Build
      run: msbuild Xamarin.Forms.sln /p:Configuration=Release /p:BUILDVERSION="${GITHUB_RUN_NUMBER}" /p:BUILD_BUILDID="${GITHUB_RUN_NUMBER}" /restore
    - name: Build (.NET 8 / iOS)
      run: dotnet build Xamarin.Forms.Platform.iOS /p:Configuration=Release /p:Net8Build=true /p:BUILDVERSION="${GITHUB_RUN_NUMBER}" /p:BUILD_BUILDID="${GITHUB_RUN_NUMBER}" /p:_SdkIgnoreMSBuildCoreWarning=true /p:_ExtrasSkipTargetsCheck=true /restore
    - name: Pack
      run: |
        $version = Get-Content -Path .XamarinFormsVersionFile.txt
        nuget.exe pack .nuspec/Xamarin.Forms.nuspec -Properties "Version=${version};Configuration=Release"
      shell: pwsh
    - uses: actions/upload-artifact@master
      with:
        name: build-artifacts
        path: Xamarin.Forms.*.nupkg

  publish:
    permissions:
      packages: write
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/net8'
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
        include-prerelease: true
    - uses: actions/download-artifact@master
      with:
        name: build-artifacts
        path: build-artifacts
    - name: Publish
      if: ${{ github.event_name == 'push' }}
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/filipnavara/index.json -n github
        find build-artifacts -name '*.nupkg' | xargs -i dotnet nuget push {} -s github --api-key ${{ secrets.GITHUB_TOKEN }}
